name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [clang]
    steps:
    - name: install compiler
      run: |
        yes | sudo wget -qO- https://apt.llvm.org/llvm.sh | sudo bash -s -- 18
        ls
        which bash
        clang --version
        make
    - uses: actions/checkout@v4
