name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [clang]
    steps:
    - name: compile
      run: |
        yes | wget -qO- https://apt.llvm.org/llvm.sh | bash -s -- 18
        make
    - uses: actions/checkout@v4
