name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [clang-19]
    steps:
    - name: install compiler
      run: |
        sudo apt-get install libc++-dev
        yes | sudo wget -qO- https://apt.llvm.org/llvm.sh | sudo bash -s -- 19
        git clone https://github.com/Henkeboi/hk_chess
        cd hk_chess
        make ubuntu
    - uses: actions/checkout@v4
