name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [clang-19]
    steps:
    - name: compile
      run: |
        sudo apt-get update && sudo apt-get install libc++-dev libcurl-dev
        yes | sudo wget -qO- https://apt.llvm.org/llvm.sh | sudo bash -s -- 19
        git clone https://github.com/Henkeboi/hk_chess
        cd hk_chess
        make ubuntu
    - name: unit_tests
      run: |
        cd hk_chess
        sudo apt-get update
        sudo apt-get install libgtest-dev libtool autoconf build-essential pkg-config automake tcsh -y 
        make ubuntu -C tests/board_test
        tests/board_test/main
        make ubuntu -C tests/zobrist_test
        tests/zobrist_test/main
    - uses: actions/checkout@v4
